[package]
name = "inference"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
llama-cpp-2 = "0.1.102"
rstest = "0.25.0"
thiserror = "2.0.12"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
